apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp
spec:
  selector:
    matchLabels:
      name: votingapp
  replicas: 2
  template:
    metadata:
      labels:
        name: votingapp
    spec:
      containers:
        - name: votingapp
          image: simplonasa/azure_voting_app:TAG
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m
          env:
            - name: STRESS_SECS
              value: "2"
            - name: REDIS
              value: "service-redis"
            - name: REDIS_PWD
              value: "$(REDIS_PWD)"
            - name: REDIS_PWD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PWD
          ports:
            - containerPort: 80
